baseurl = "https://jmcelwa.in"
languageCode = "en-US"
title = "Blog"
theme = "hugo-theme-one"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    author = "James McElwain"
    locale = "en-US"
    # rootlink = "/"
    # rootlink specifies where Root in menu.html links to. If it's not set then baseurl will be used.
