baseURL = "https://jmcelwa.in/"
languageCode = "en-us"
title = "James McElwain"
theme = "jmcelwain"

# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    navigation = ["about.md"]